Temp
LOLBAS-Project/LOLBAS pull request #192
Opened 2022-01-20 13:02 UTC by mrd0x

2022-01-24 09:06 UTC, wietze commented
The `msedge.exe` trick has been spotted in the wild: https://twitter.com/SBousseaden/status/1485283092008951815 

Nice one @mrd0x - will properly review your entire PR soon.

2022-04-05 19:27 UTC, mrd0x commented
Createdump.exe was previously mentioned: https://twitter.com/bopin2020/status/1366400799199272960

2022-05-15 19:28 UTC, wietze requested changes
Thanks for these contributions! I made a couple of minor tweaks and have a few questions - see below.

2022-05-15 19:28 UTC, wietze commented on yml/OtherMSBinaries/Devinit.yml
> +    Usecase: Download file from Internet
I noticed the MSI file gets deleted if the installation of the MSI was unsuccessful; wouldn't that make "execution" the main goal of this technique? Since the MSI has to install correctly for the file to remain on disk, I figure there won't be much else you can do with the file once it has been installed anyway?

2022-05-15 19:28 UTC, wietze commented on yml/OtherMSBinaries/Createdump.yml
> +    Privileges: SYSTEM
Does this mean it requires SYSTEM privileges as opposed to regular elevated ("administrator") privs?

2022-05-15 19:28 UTC, wietze commented on yml/OSBinaries/Msedge.yml
> +    Description: Edge will launch and install the file. A harmless file extension (e.g. .txt, .zip) should be appended to avoid SmartScreen.
Same here - "install the file" seems not entirely correct, perhaps you meant "download the file"?

2023-01-02 00:43 UTC, mrd0x commented on yml/OSBinaries/msedge.yml
> +    Description: Edge will launch and install the file. A harmless file extension (e.g. .txt, .zip) should be appended to avoid SmartScreen.
Yes I meant download the file. Sorry for the mix up.

2023-01-02 00:44 UTC, mrd0x commented on yml/OtherMSBinaries/Devinit.yml
> +    Usecase: Download file from Internet
You are right, the category should be execution rather than download.

2023-01-02 00:46 UTC, mrd0x commented on yml/OtherMSBinaries/Createdump.yml
> +    Privileges: SYSTEM
Yes this requires SYSTEM privileges not just administrator privileges.

2023-01-02 00:46 UTC, mrd0x commented on yml/OSBinaries/Msedge.yml
> +    Description: Edge will launch and install the file. A harmless file extension (e.g. .txt, .zip) should be appended to avoid SmartScreen.
Yes I meant download the file. Sorry for the mix up.

2023-01-02 00:52 UTC, mrd0x commented on yml/OSBinaries/Explorer.yml
> +    Description: Explorer will launch Microsoft Edge and install the file. A harmless file extension (e.g. .txt, .zip) should be appended to avoid SmartScreen.
Explorer will launch the default browser when it sees the HTTP/S protocol. So this may not be a LOLBIN as explorer isn't the one performing the download (not install).

User interaction is not required if a harmless extension is appended to the file.

2023-03-31 12:45 UTC, wietze approved these changes
🎉

2023-03-31 12:46 UTC, wietze commented
Thanks for your additions @mrd0x , much appreciated.

2023-03-31 12:46 UTC, merged