Add Desk.cpl
LOLBAS-Project/LOLBAS pull request #207
Opened 2022-04-21 08:41 UTC by LuxNoBulIshit

Launch an scr payload by calling InstallScreenSaver

2022-04-21 15:59 UTC, wietze requested changes
Nice find, few questions/remarks from me.

2022-04-21 15:59 UTC, wietze commented on yml/OSLibraries/desk.yml
> +  - IOC: conhost.exe spawning unexpected processes
This is probably not updated after copy/pasting

2022-04-21 15:59 UTC, wietze commented on yml/OSLibraries/desk.yml
> +  - Link: https://file.io/x3CRqMdX95i0
What kind of file is this,  is this a sample `.scr` file? If so, could you please put the source code on GitHub and link to that instead?

2022-04-21 15:59 UTC, wietze commented on yml/OSLibraries/desk.yml
> +  - Command: "rundll32.exe desk.cpl,InstallScreenSaver C:\temp\file.scr"
Aren't `.scr` files regular PE files (i.e. `.exe`) with a different extension? I was hoping the following would work, but it doesn't seem to:
```
rundll32 desk.cpl,InstallScreenSaver c:\windows\system32\calc.exe
```
Is this expected? If so, can you elaborate on what the requirements for the `.scr` file are?

2022-04-21 15:59 UTC, wietze commented on yml/OSLibraries/desk.yml
> +  - Path: C:\Windows\WinSxS\wow64_microsoft-windows-desk_31bf3856ad364e35_10.0.19041.1_none_6cc8911cecbbbf87\desk.cpl
These paths change regularly and can change from system to system,  so let's omit them from the entry.

2022-04-23 02:36 UTC, LuxNoBulIshit commented on yml/OSLibraries/desk.yml
> +  - Link: https://file.io/x3CRqMdX95i0
https://file.io/x3CRqMdX95i0

here you can find the scr file that execute calculator .

2022-04-23 11:12 UTC, wietze commented on yml/OSLibraries/desk.yml
> +  - Link: https://file.io/x3CRqMdX95i0
Can you upload the source code to a public space such as GitHub and link to that instead please?

2022-04-23 13:23 UTC, LuxNoBulIshit commented on yml/OSLibraries/desk.yml
> +  - Command: "rundll32.exe desk.cpl,InstallScreenSaver C:\temp\file.scr"
Change the calc.exe to calc.scr and run it 👍 

its will work ( just did ).

2022-04-23 13:24 UTC, LuxNoBulIshit commented on yml/OSLibraries/desk.yml
> +  - Link: https://file.io/x3CRqMdX95i0
Change the calc.exe to calc.scr and run it 👍

its will work ( just did ).

2022-04-23 13:28 UTC, LuxNoBulIshit commented on yml/OSLibraries/desk.yml
> +  - Path: C:\Windows\WinSxS\wow64_microsoft-windows-desk_31bf3856ad364e35_10.0.19041.1_none_6cc8911cecbbbf87\desk.cpl
totally agree 👍

2022-04-26 09:46 UTC, LuxNoBulIshit commented on yml/OSLibraries/desk.yml
> +  - Command: "rundll32.exe desk.cpl,InstallScreenSaver C:\temp\file.scr"
@wietze 

did you manage to make it work ?

2022-04-27 10:11 UTC, wietze approved these changes

2022-04-27 10:15 UTC, merged

2022-04-27 10:16 UTC, wietze commented
After a few final tweaks, it has now been merged into the project. Thank you for your contribution!