Add sigma reference
LOLBAS-Project/LOLBAS pull request #213
Opened 2022-05-07 08:06 UTC by frack113

Just add missing SigmaHQ references

2022-05-15 18:45 UTC, wietze requested changes
Thanks for this, one question about one of the rules (see below)

2022-05-15 18:45 UTC, wietze commented on yml/OSBinaries/Ttdinject.yml
> +  - Sigma: https://github.com/SigmaHQ/sigma/blob/35a7244c62820fbc5a832e50b1e224ac3a1935da/rules/windows/image_load/image_load_tttracer_mod_load.yml
Did you perhaps mean to add this one to the `tttracer` entry? All the resources in the Sigma rule point to that executable.

2022-05-15 19:22 UTC, frack113 commented on yml/OSBinaries/Ttdinject.yml
> +  - Sigma: https://github.com/SigmaHQ/sigma/blob/35a7244c62820fbc5a832e50b1e224ac3a1935da/rules/windows/image_load/image_load_tttracer_mod_load.yml
This sigma rule detect load dll '\ttdrecord.dll' or '\ttdwriter.dll' or  '\ttdloader.dll'.
Ttdinject.exe load TTDLoader.dll so the rule trigger.

2022-05-15 19:29 UTC, frack113 commented on yml/OSBinaries/Ttdinject.yml
> +  - Sigma: https://github.com/SigmaHQ/sigma/blob/35a7244c62820fbc5a832e50b1e224ac3a1935da/rules/windows/image_load/image_load_tttracer_mod_load.yml
As it can be disturbing, I will work on a rule with Ttdinject.exe as parent this week .

2022-05-17 04:37 UTC, frack113 commented on yml/OSBinaries/Ttdinject.yml
> +  - Sigma: https://github.com/SigmaHQ/sigma/blob/35a7244c62820fbc5a832e50b1e224ac3a1935da/rules/windows/image_load/image_load_tttracer_mod_load.yml
It is fix with the new rules 😄

2022-05-17 08:17 UTC, wietze commented on yml/OSBinaries/Ttdinject.yml
> +  - Sigma: https://github.com/SigmaHQ/sigma/blob/35a7244c62820fbc5a832e50b1e224ac3a1935da/rules/windows/image_load/image_load_tttracer_mod_load.yml
Great stuff, looking good 👌

2022-05-17 08:18 UTC, merged

2022-05-17 08:18 UTC, wietze commented
Great additions, thank you for your contribution