Add/Update LOLBINS
LOLBAS-Project/LOLBAS pull request #229
Opened 2022-06-13 23:02 UTC by nasbench

Hi,

This PR covers the following changes:
- Creation of New LOLScript "Launch-VsDevShell.ps1"  (https://twitter.com/nas_bench/status/1535981653239255040)
- Update WSL LOLBIN with new Sigma Rules and CLI variation (https://twitter.com/nas_bench/status/1535431474429808642)
- Update Adplus LOLBIN with new Sigma Rules and CLI variation (https://twitter.com/nas_bench/status/1534916659676422152 + https://twitter.com/nas_bench/status/1534915321856917506)
- Update CDB LOLBIN with new Sigma Rules and CLI variation (https://twitter.com/nas_bench/status/1534957360032120833)
- Update PCWrun LOLBIN with new CLI variation related to Follina (https://twitter.com/nas_bench/status/1535663791362519040) and Sigma Rules
- Update Msdt LOLBIN with new Sigma rules and CLI variations (https://twitter.com/nas_bench/status/1531944240271568896)

2022-07-27 12:53 UTC, wietze commented
Just saw your tweet, cool stuff. Will do my best to review this PR soon, it's a big one!

2022-11-03 22:06 UTC, nasbench commented
Reminder :)

2022-11-08 15:54 UTC, wietze requested changes
Great work! couple of comments from me, if you would be able to address them I'll be able to merge it. Thanks!

2022-11-08 15:54 UTC, wietze commented on yml/OSBinaries/Msdt.yml
> +  - Command: msdt.exe /id PCWDiagnostic /skip force /param "IT_LaunchMethod=ContextMenu IT_BrowseForFile=/../../$(<command>).<exe/msi>"
Just wanted to check, I can't get this to work on Windows 11 21H2, do we know if this specific version has been patched by Microsoft?

2022-11-08 15:54 UTC, wietze commented on yml/OSBinaries/Pcwrun.yml
> +  - Command: Pcwrun.exe /../../$(<payload>).exe
Same here, probably whatever the answer to the previous question is applies here too.

2022-11-08 15:54 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsWherePath "<executable>"
I'm assuming this runs with `powershell -ep bypass -file` as a prefix - this should be updated.

2022-11-08 15:54 UTC, wietze commented on yml/OSBinaries/Pcwrun.yml
> +    Description: Levreage the MSDT follina vulnerability through Pcwrun to execute arbitrary commands and binaries
Leverage

2022-11-08 15:54 UTC, wietze commented on yml/OSBinaries/Pcwrun.yml
> +    MitreID: T1218
Should be T1202

2022-11-08 15:54 UTC, wietze commented on yml/OSBinaries/Msdt.yml
> +    MitreID: T1218
Should be T1202

2022-11-08 15:54 UTC, wietze commented on yml/OSBinaries/Msdt.yml
> +    Usecase: Execute code bypass Application whitelisting
Application whitelisting -> application allowlisting

2022-11-08 15:54 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsWherePath "<executable>"
Still works with VS22, used the following command:
```powershell -ep bypass -f Launch-VsDevShell.ps1 -VsWherePath "c:\windows\system32\calc.exe"```

2022-11-08 15:54 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsWherePath "<executable>"
I'd recommend replacing `<executable>` with `c:\windows\system32\calc.exe` to provide a practical example AND to highlight that a full, absolute path is required.

2022-11-08 15:54 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsInstallationPath "/../../../../../; <command> ;"
Same comment about powershell.exe applies here, as well as the placeholder comment

2022-11-08 15:54 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsInstallationPath "/../../../../../; <command> ;"
Funnily enough, here the opposite applies: it did not work for `c:\windows\system32\calc.exe` but it DID work for `calc.exe`. Again, i'd recommend using calc as an example here.

2022-11-08 15:54 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +    Description: Execute binaries and commands  from the context of the signed script using the "VsInstallationPath" flag
redundant space

2022-11-08 15:54 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsWherePath "<executable>"
Perhaps also consider leaving out the full path in both examples and just use `Launch-VsDevShell.ps1` as the paths change per VS version. Your `full_path` section below should help locating it.

2022-11-08 15:54 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Sigma:
Empty sections can be removed

2022-11-08 15:54 UTC, wietze commented on yml/OtherMSBinaries/Wsl.yml
> +  - Command: wsl.exe --system <command>
Again, I'd add your calc.exe example from your tweet as this is non-trivial

2022-11-08 15:54 UTC, wietze commented on yml/OtherMSBinaries/Cdb.yml
> +  - Command: cdb.exe -c $<"[path-to-debugger-script]" <command>
Could you provide practical example (e.g. calc) here as well? Is debugger script expected to be in a certain format? Does it need to exist at all?

2022-11-08 15:54 UTC, wietze commented on yml/OtherMSBinaries/Adplus.yml
> +  - Command: adplus.exe -c <config>
can you replace the placeholder with a sample filename, and maybe create a GitHub Gist with the content you used? If you add that gist to the resources section, i think it'd be very useful for people who want to use/test this

2022-11-08 15:54 UTC, wietze commented on yml/OtherMSBinaries/Adplus.yml
> +  - Command: adplus.exe -crash -o <outputfolder> -sc <command>
Same here, can you replace the placeholders? And am I right in assuming output folder is required?

2022-11-08 15:54 UTC, wietze commented on yml/OSBinaries/Msdt.yml
> +  - Command: msdt.exe /id PCWDiagnostic /skip force /param "IT_LaunchMethod=ContextMenu IT_BrowseForFile=/../../$(<command>).<exe/msi>"
If so, perhaps add it as a precondition to the description line.

2022-11-08 15:54 UTC, wietze commented on yml/OtherMSBinaries/Adplus.yml
> +    Description: Execute arbitrary commands or dump process memory using config adplus file
If you can do both with this approach, you may 'duplicate' the entry but update the category to `Dump`, so it will be listed under both Execute and Dump.

2022-11-08 19:52 UTC, nasbench commented on yml/OSBinaries/Msdt.yml
> +  - Command: msdt.exe /id PCWDiagnostic /skip force /param "IT_LaunchMethod=ContextMenu IT_BrowseForFile=/../../$(<command>).<exe/msi>"
I've updated the placeholders and added a description stating that this will not work after the June security update (which is the one that patched follina) and fixed the path traversal issue

2022-11-08 19:52 UTC, nasbench commented on yml/OSBinaries/Pcwrun.yml
> +  - Command: Pcwrun.exe /../../$(<payload>).exe
Done

2022-11-08 19:53 UTC, nasbench commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsWherePath "<executable>"
I've applied your suggestion of dropping the full path and replacing placeholders. But to my understanding, you don't require the `powershell -ep bypass` because the script is signed by MS

2022-11-08 19:53 UTC, nasbench commented on yml/OSBinaries/Pcwrun.yml
> +    Description: Levreage the MSDT follina vulnerability through Pcwrun to execute arbitrary commands and binaries
Done

2022-11-08 19:54 UTC, nasbench commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsInstallationPath "/../../../../../; <command> ;"
Done

2022-11-08 19:56 UTC, nasbench commented on yml/OtherMSBinaries/Cdb.yml
> +  - Command: cdb.exe -c $<"[path-to-debugger-script]" <command>
I've added the script to a gist https://gist.github.com/nasbench/d9c15864f1e21bdd8b7cf55997b45f4b#file-debug-script-txt

Just for completion's sake. To generate this script, just execute adplus with the "-crash" flag as stated in the Adplus lolbin and you'll have a debugger script example in the output folder

2022-11-08 19:57 UTC, nasbench commented on yml/OtherMSBinaries/Adplus.yml
> +  - Command: adplus.exe -c <config>
I've added an example config here https://gist.github.com/nasbench/e34ca2cd90e3a845a558a102a4f607da

This config can be used to both dump and execute stuff. 

Ps: In my testing the "dump" is required so the "settings" portion of that file which specifies what process to dump is necessary and the process must exist

2022-11-08 19:58 UTC, nasbench commented on yml/OtherMSBinaries/Adplus.yml
> +    Description: Execute arbitrary commands or dump process memory using config adplus file
I've duplicated the entry for more clarity and modified both the permissions and the category

2022-11-08 19:59 UTC, nasbench commented
Thanks for taking the time to review this @wietze. I've updated the files accordingly, please check when you have the time :)

2022-11-11 15:38 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsWherePath "<executable>"
On vanilla Windows 11 (21H2):
![image](https://user-images.githubusercontent.com/2811785/201373747-d6da9115-a653-48eb-9e28-85183973647f.png)
![image](https://user-images.githubusercontent.com/2811785/201373805-6a6b35ea-581a-4d31-9ca2-69f62303cee2.png)

This seems consistent with the [Microsoft Docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3), which claim that on workstations (i.e. non-Server editions), the default policy is 'restricted', which does NOT allow any files to be run. 

In fairness, you could use `powershell -ep RemoteSigned` which may be less detection-prone:
![image](https://user-images.githubusercontent.com/2811785/201374076-ab5e5364-d87b-493c-b786-9c2ca7ec1f6e.png)

2022-11-11 15:40 UTC, wietze commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsWherePath "<executable>"
So TL;DR, I have prefixed your entries with `powershell -ep RemoteSigned`, please let me know if you're happy with this change. If so, I can merge the entire PR.

2022-11-11 15:55 UTC, nasbench commented on yml/OSScripts/Launch-VsDevShell.yml
> +  - Command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Launch-VsDevShell.ps1 -VsWherePath "<executable>"
You're right. I tricked myself in my lab as the Exec policy was `bypass` all the time. Alright then we put it as you suggested.

2022-11-11 16:41 UTC, wietze approved these changes
Thanks for addressing the comments, again - superb work. Thank you for your contributions!

2022-11-11 16:42 UTC, merged