adding badges
LOLBAS-Project/LOLBAS pull request #256
Opened 2022-09-18 17:20 UTC by d1vious

Adds badges to README.md for the CI job [yaml-linting](https://github.com/LOLBAS-Project/LOLBAS/blob/master/.github/workflows/yaml-linting.yml) and a script (`scripts/lolbas_count.py`) to calculate the lolbas count that generates the [svg badge](https://lolbas-project.s3.us-east-2.amazonaws.com/lolbas_count.svg), right now I uploaded it to a public s3 bucket
 
It automatically updates the svg using a newly created github action workflow called: `upload_lolbas_count` .. also included creds on the project secrets.

![image](https://user-images.githubusercontent.com/1476868/190841533-246acb99-6f21-4d5e-a18f-1b388373af02.png)

2022-10-04 12:44 UTC, wietze requested changes
Hey @d1vious , I think this solution is somewhat over-engineered and can be simplified without the need for GitHub Actions, Amazon buckets, and what not.

Have a look at LOLBAS-Project/LOLBAS-Project.github.io#12 - this adds a dynamically-updating SVG with a counter of the number of LOLBAS entries, based what's on the website. Because the website is always in sync with the main repo, this should achieve the exact same you're trying to do here.

My suggestion would therefore be:
- Remove the `lolbas_count.yml` workflow, as well as thee `scripts/` folder and `pyproject.toml` file. 
- Fix the outstanding issues in `README.md`.

2022-10-04 12:44 UTC, wietze commented on README.md
> +        <img src="https://img.shields.io/github/workflow/status/splunk/security_content/build-and-validate/develop" /></a>
Wrong URL? Image points to Splunk repo

2022-10-04 12:44 UTC, wietze commented on README.md
> +        <img src="https://lolbas-project.s3.us-east-2.amazonaws.com/lolbas_count.svg" /></a>
Replace with 
```<img src="https://lolbas-project.github.io/assets/lolbas-count.svg" /></a>```
once LOLBAS-Project/LOLBAS-Project.github.io#12 has been merged

2022-10-04 12:44 UTC, wietze commented on README.md
> +    <a href="https://github.com/splunk/security_content">
Wrong URL?

2022-10-04 12:44 UTC, wietze commented on README.md
> +        <img src="https://img.shields.io/github/stars/splunk/security_content?style=social" /></a>
Wrong URL?

2022-10-04 12:44 UTC, wietze commented on README.md
> +</p>
These lines can be removed

2023-01-02 14:52 UTC, josehelps commented on README.md
> +        <img src="https://img.shields.io/github/workflow/status/splunk/security_content/build-and-validate/develop" /></a>
yes this was a mistake, fixing.

2023-01-02 14:56 UTC, josehelps commented on README.md
> +        <img src="https://lolbas-project.s3.us-east-2.amazonaws.com/lolbas_count.svg" /></a>
hey quick question how does https://github.com/LOLBAS-Project/LOLBAS-Project.github.io/pull/12/files#diff-455017c6da03ae820b67ffa00b9b4e2f1c7c6cda78d8553ea74c062a44babec0R19 .. specifically `{{ site.lolbas | size }}` gets calculated here? I agree though this is a much cleaner solution, will remove the script/pyproject files etc..

2023-01-03 02:32 UTC, josehelps commented on README.md
> +        <img src="https://lolbas-project.s3.us-east-2.amazonaws.com/lolbas_count.svg" /></a>
looking at this closer, assuming this is coming from the Jekyll collections https://github.com/LOLBAS-Project/LOLBAS-Project.github.io/blob/master/_config.yml#L8-L10 right?

2023-01-03 02:33 UTC, josehelps commented on README.md
> +    <a href="https://github.com/splunk/security_content">
yep fixing!

2023-01-03 02:33 UTC, josehelps commented on README.md
> +        <img src="https://img.shields.io/github/stars/splunk/security_content?style=social" /></a>
correct :-) I will fix it, sloppy PR on my part.

2023-01-03 02:33 UTC, josehelps commented on README.md
> +</p>
updated the file!

2023-01-03 02:45 UTC, josehelps commented
@wietze thank you for the awesome feedback, implemented the changes, and yes my approach was way more complex than it needed to be thank you for pointing that out. Reminded me a bit of https://giphy.com/gifs/engineering-rube-goldberg-machine-mYqaRkXyoGbcY

2023-02-25 18:54 UTC, wietze approved these changes

2023-02-25 18:56 UTC, merged