DevTunnels - Other MS Binary for Data Exfiltration
LOLBAS-Project/LOLBAS pull request #327
Opened 2023-09-16 00:25 UTC by deFr0ggy

Microsoft has released a functionality, which is very new and enables the developers to use port forwarding on their systems to expose locally hosted applications over the internet. This functionality aids developers to expose their systems directly on the internet without the need to host their applications on any server. The functionality is like Live Preview in the VSCode which allows the developers to host their websites locally but now with added functionality, they can forward the local ports over the internet. Thus, anyone on the internet can access the applications developed.

As per my research, the binary can be used to open up forwarded ports on the local system and then access the data over the internet via the generated dev tunnel URLs. 

Research can be found on the below link.

https://cydefops.com/vscode-data-exfiltration

The binary will be covered in the second part of the research which will be published soon, however same is achieved via devtunnels within the VScode which executes the same binary.

2023-09-16 00:31 UTC, deFr0ggy reviewed
Validated the YAML.

2023-09-16 00:37 UTC, deFr0ggy reviewed
Updated the Category!

2023-09-16 00:40 UTC, deFr0ggy reviewed
updated category!

2023-09-16 00:43 UTC, deFr0ggy reviewed
updated MitreID

2023-09-23 20:49 UTC, deFr0ggy commented
Published detailed research article on the same.

https://cydefops.com/devtunnels-unleashed

2023-10-04 03:43 UTC, xenoscr approved these changes
Looks good, thank your for the pull request @deFr0ggy.

2023-10-04 06:28 UTC, deFr0ggy commented
Much Appreciated @xenoscr! Looking forward to have it merged!

2023-10-09 07:10 UTC, api0cradle requested changes
Change privileges to either "User" or "Administrator"

2023-10-09 07:29 UTC, deFr0ggy reviewed
Privilege's have been changed to User

2023-10-12 09:47 UTC, deFr0ggy commented
@api0cradle do let me know if there are any other changes required for the same.

2023-10-14 22:05 UTC, api0cradle approved these changes

2023-10-14 22:05 UTC, merged