Updates in Stordiag.exe
LOLBAS-Project/LOLBAS pull request #394
Opened 2024-08-30 16:04 UTC by Ekitji

Where it on Windows 11 also supports the filename powershell.exe

2024-09-07 14:06 UTC, wietze requested changes
Thanks for your suggestion, @Ekitji - seem my feedback below.

2024-09-07 14:06 UTC, wietze commented on yml/OSBinaries/Stordiag.yml
> +  - Alias: stordiag.exe  # PE Original filename
Other than the casing, this is identical to the entry's name. Can you please remove it?

2024-09-07 14:06 UTC, wietze commented on yml/OSBinaries/Curl.yml
> +---
Could you please remove `curl` from your pull request?

2024-09-07 14:06 UTC, wietze commented on yml/OSBinaries/Stordiag.yml
> +    OperatingSystem: Windows 10
Is there a reason you're removing Windows 11 here?

2024-09-07 14:06 UTC, wietze commented on yml/OSBinaries/Stordiag.yml
> +    Description: Once executed, Stordiag.exe will execute schtasks.exe and powershell.exe - if stordiag.exe is copied to a folder and an arbitrary executable is renamed to one of these names, stordia
Is the difference with the previous entry that on windows 11 it executes `powershell` instead of `systeminfo` and `fltmc`?

2024-09-07 21:45 UTC, Ekitji commented on yml/OSBinaries/Stordiag.yml
> +  - Alias: stordiag.exe  # PE Original filename
yes im removing it.. its there to include the original filename ..

2024-09-07 21:45 UTC, Ekitji commented on yml/OSBinaries/Curl.yml
> +---
Done

2024-09-07 21:46 UTC, Ekitji commented on yml/OSBinaries/Stordiag.yml
> +    OperatingSystem: Windows 10
there is a difference on whats working on windows 10 and windows 11.. 

separating them so its more clear what works on what system.

2024-09-07 21:47 UTC, Ekitji commented on yml/OSBinaries/Stordiag.yml
> +    Description: Once executed, Stordiag.exe will execute schtasks.exe and powershell.exe - if stordiag.exe is copied to a folder and an arbitrary executable is renamed to one of these names, stordia
yes thats correct.

2024-09-07 21:50 UTC, Ekitji commented
Have changed the requested parts

2024-09-10 12:31 UTC, wietze commented
Thanks @Ekitji

2024-09-10 12:31 UTC, merged